### ISSUE TITLE
Slicing Enquiry

### ISSUE THREAD

**Issue by ritchieng** [hardmaru/supercell#3]
Thanks for open-sourcing your supercell, it's really useful.

Why are you slicing based on `0:self.num_units` and for hyper_state based on `self.num_units:`? 

```
h = total_h[:, 0:self.num_units]
c = total_c[:, 0:self.num_units]
self.hyper_state = tf.concat(1, [total_h[:,self.num_units:], total_c[:,self.num_units:]])

```
Thanks!

**Comment by ritchieng** [comment]
Managed to debug and found that you're just splitting what you concatenated.

**Comment by hardmaru** [comment]
Cool.
